const LANGUAGE = {
  en: {
    nav1: "Why Startline",
    nav2: "Price",
    nav3: "Resources",
    nav4: "Support",
    nav5: "Contact",
    nav6: "Login",
    nav7: "Join",
    index_title: "We are the Startline",
    index_slogan: "Where innovation for startups and corporates begins",
    index_context: "We empower the collaborative partnership between startups and corporates",
    join_now: "Join Now",
    weekly_startline: "THIS WEEK ON STARTLINE",
    our_product: "OUR PRODUCT",
    product_slogan: "Empowering futures at the Startline for startups and corporates",
    feature_title_1: "PERSONALIZED",
    feature_slogan_1: "Tailored recommendations that fit your unique needs",
    feature_content_1: "Everyone has different needs. Tell us what you want and we will provide it to you!",
    learn_more_1: "Learn More",
    learn_more_2: "Learn More",
    learn_more_3: "Learn More",
    feature_title_2: "TIMELY INSIGHTS",
    feature_slogan_2: "Real-time data platform with up-to-date information",
    feature_content_2: "We want to keep you up to date. Our platform runs 24/7 to find the latest information.",
    feature_title_3: "NEW CONNECTIONS",
    feature_slogan_3: "An interactive social channel to expand your network",
    feature_content_3:
      "Whether you are a startup or a corporate, we got it covered. Join our ecosystem to be connected with the trend setting companies!",
    simeff: "Simple, but efficient",
    simeff_title: "Your start-up data intelligence platform - ready to use in 5 mins",
    simeff_content: "Use Startline Free",
    simeff_demo: "Request a Free Demo",
    partners_clients: "Partners and Clients",
    whatwedo: "WHAT WE DO",
    whatwedo_slogan: "We see problems and we want to solve it for you!",
    whatwedo_content:
      "Centralized platforms are burning bridges between startups and corporates, making it harder to access valuable information, hindering business growth, and driving up costs.",
    get_started: "Get Started",
    questions: "Questions? Talk to us",
    questions_slogan: "We are here around the clock to assist you",
    questions_content: "Try Startline Now",
    questions_contact: "Contact Us",
    problem_1: "THE PROBLEM",
    problem_title_1: "Centralized platforms burn bridges between startups and corporates",
    problem_topic_low_outreach: "Low Outreach",
    problem_content_low_outreach:
      "Start-ups struggle to find effective channels to showcase their products, while corporations face difficulty in discovering innovative solutions for their business needs.",
    problem_topic_data_inaccuracy: "Data Inaccuracy",
    problem_content_data_inaccuracy:
      "Outdated and unverified data hampers the ability to find relevant solutions or accurately identify corporate needs, leading to unreliable searches.",
    problem_topic_complex_engagement: "Complex Engagement",
    problem_content_complex_engagement:
      "Corporates and startups often have prolonged engagement processes, as each party struggles to fully understand the other's need and expectations.",
    problem_topic_lack_of_manpower: "Lack of Manpower",
    problem_content_lack_of_manpower:
      "There are insufficient resources and manpower to maintain strong connections between start-ups and corporations.",
    problem_topic_poor_visualization: "Poor Visualization",
    problem_content_poor_visualization:
      "Poorly structured interfaces and lack of personalization makes it challenging for users to efficiently find critical information.",
    lets_fix: "Let's Fix It",
    solution: "OUR SOLUTION",
    solution_title: "Startline is a social platform for corporates and startups",
    solution_startup_slogan: "For Startups",
    solution_startup_content: "We amplify your tech and create pathways for collaboration with those who need it most.",
    solution_corporate_slogan: "For Corporates",
    solution_corporate_content: "We connect you with emerging innovators who have the perfect solutions to your challenges.",
    try_startline: "Try Startline Now",
    how_it_works: "HOW IT WORKS",
    how_it_works_slogan_1: "Startline fuses and validates multiple data sources to provide the best information",
    how_it_works_content_1: "We pick out what you need from our own database that is accurate and up-to-date",
    how_it_works_option_1: "Multiple Data Sources",
    how_it_works_option_content_1: "We gather information from various sources.",
    how_it_works_option_2: "Company Profile",
    how_it_works_option_content_2: "Our curated databases outline each company’s information",
    how_it_works_option_3: "User Feedback",
    how_it_works_option_content_3: "Our matching algorithm constantly improves with feedback",
    how_it_works_slogan_2: "Our data-driven technology has an AI model optimized just for you",
    how_it_works_content_2:
      "We leverage AI to deliver clear, relevant, and timely insights that will help corporates and startups find each other",
    how_it_works_1: "HOW IT WORKS",
    how_it_works_title_integrate_data: "Integrating Data",
    how_it_works_content_integrate_data: "We transform the accumulated data into structured datasets.",
    how_it_works_title_processing_data: "Processing Data",
    how_it_works_content_processing_data: "We leverage machine learning to categorize, tag, and evaluate companies.",
    how_it_works_title_creating_insights: "Creating Insights",
    how_it_works_content_creating_insights:
      "Through AI, we pinpoint the information that matters the most and match you with companies that meet your needs.",

    how_it_works_title_integrate_data_1: "Integrating Data",
    how_it_works_content_integrate_data_1: "We transform the accumulated data into structured datasets.",
    how_it_works_title_processing_data_1: "Processing Data",
    how_it_works_content_processing_data_1: "We leverage machine learning to categorize, tag, and evaluate companies.",
    how_it_works_title_creating_insights_1: "Creating Insights",
    how_it_works_content_creating_insights_1:
      "Through AI, we pinpoint the information that matters the most and match you with companies that meet your needs.",

    how_it_works_title_integrate_data_2: "Integrating Data",
    how_it_works_content_integrate_data_2: "We transform the accumulated data into structured datasets.",
    how_it_works_title_processing_data_2: "Processing Data",
    how_it_works_content_processing_data_2: "We leverage machine learning to categorize, tag, and evaluate companies.",
    how_it_works_title_creating_insights_2: "Creating Insights",
    how_it_works_content_creating_insights_2:
      "Through AI, we pinpoint the information that matters the most and match you with companies that meet your needs.",

    how_it_works_slogan_3: "Our match-making process ensures that each request meets a solution",
    why_startline_title_exceptional_data_quality: "Exceptional data quality",
    why_startline_content_exceptional_data_quality: "Our AI model scrapes and cleans until you are satisfied with what you have.",
    why_startline_title_indepth_data: "In-depth data",
    why_startline_content_indepth_data: "We deliver the real stories behind companies. These stories help you verify what you really need.",
    why_startline_title_extensive_access: "Extensive access",
    why_startline_content_extensive_acess: "Access to tech markets that no one else has.",
    why_startline_title_efficiency: "Efficiency at its finest",
    why_startline_content_efficiency: "The simplest, most efficient way to look for what you need.",
    why_startline_title_complete_solution: "Complete solution",
    why_startline_content_complete_solution: "We provide a solution rather than a pile of databases.",
    why_startline_title_fully_automated: "Fully automated",
    why_startline_content_fully_automated:
      "Our AI model allows us to work 24/7 to satisfy your needs and provide new information every day.",
    pricing_1: "Price",
    pricing_slogan: "Choose the plan that matches your needs",
    pricing_free: "Free Forever",
    pricing_free_price: "$0",
    pricing_free_tag: "Global Database",
    pricing_free_feature_1: "Unlock Startline's AI-powered Matching Features",
    pricing_free_feature_2: "Search 100 company profiles per month with basic content",
    pricing_free_feature_3: "Access to basic information",
    pricing_business: "Business",
    pricing_business_price: "$49/month",
    pricing_business_tag_1: "Global Database",
    pricing_business_tag_2: "Data Customization",
    pricing_business_feature_1: "Unlock Startline's AI-powered Matching Features",
    pricing_business_feature_2: "Search 600 company profiles per month with full content",
    pricing_business_feature_3: "Receive customized content from our dedicated success manager",
    pricing_business_feature_4: "Free upgrade to future platform features",
    pricing_enterprise: "Enterprise",
    pricing_enterprise_price: "$199/month",
    pricing_enterprise_tag_1: "Global Database",
    pricing_enterprise_tag_2: "Data Customization",
    pricing_enterprise_tag_3: "Professional Consulting Support",
    pricing_enterprise_feature_1: "Unlock Startline's AI-powered Matching Features",
    pricing_enterprise_feature_2: "Access to unlimited company profiles with full results",
    pricing_enterprise_feature_3: "Receive customized content from our assigned success manager",
    pricing_enterprise_feature_4: "Get professional consulting support from industry renowned subject matter expert",
    pricing_enterprise_feature_5: "Free upgrade to future platform features",
    pricing_enterprise_feature_6: "Collaborate with up to 5 team members",
    pricing_price_usd: "All prices are in USD",
    contact: "Contact",
    contact_question_1: "Please choose the reason for reaching out",
    contact_question_2: "Seeking detailed market information",
    contact_question_3: "Exploring potential strategic partnership opportunities",
    contact_question_4: "Interested in reviewing additional services",
    contact_question_5: "Providing feedback on the platform/service",
    contact_question_6: "Other inquiries (please specify)",
    contact_fname: "First Name",
    contact_lname: "Last Name",
    contact_company_name: "Company Name",
    contact_phone: "Phone",
    contact_email: "Email",
    contact_message: "Message",
    contact_submit: "Submit",
    price_ready_to_start: "Ready to get started?",
    price_kickstart_innovation: "Kickstart innovation with us",
    price_try_startline_now: "Try Startline Now",
    login_startup: "STARTUP",
    login_corporate: "CORPORATE",
    login_welcome_back: "Welcome Back",
    login_startup_slogan: "To championing your solutions",
    login_corporate_slogan: "To connecting you with solutions",
    login_work_email: "Work email",
    login_password: "Password",
    login_remember: "Remember me",
    login_forgot_pwd: "Forgot Password?",
    login_sign_in: "Sign In",
    login_sign_up: "Don't have an account? Sign up",
    join_title: "Welcome to Startline",
    join_slogan: "Kickstart innovation with us",
    join_username: "Username",
    join_pwd: "Password",
    join_name: "Name",
    join_work_email: "Work Email",
    join_remember: "Remember me",
    join_forgot_pwd: "Forgot Password?",
    join_tc_pp_content: "By signing up, you are agreeing to our Terms and Conditions and Privacy Policy.",
    join_sign_up: "Sign Up",
    join_sign_in: "Already have an account? Sign in",
    join1_title: "Welcome to Startline,",
    join1_select: "Select your plan",
    join1_faq_1: "Can I change my plan later?",
    join1_faq_ans_1: "Of course! You can change your plan by going to Settings > Plan Settings.",
    join1_faq_2: "Not all of my questions have been answered. Who do I reach out to?",
    join1_faq_ans_2: "Check out our support page or contact us!",
    join1_startup: "I am a Startup",
    join1_startup_content: "Showcase your product to corporate users with a personalized profile page, all for free!",
    join1_corporate_free_title: "Free",
    join1_corporate_free_price: "$0",
    join1_corporate_free_content:
      "Access 100 company profiles for essential information such as website links and employee numbers at no cost.",
    join1_corporate_business_title: "Business",
    join1_corporate_business_price: "$49 /month",
    join1_corporate_business_content:
      "Dive deeper with 600 company profiles featuring basic, product, finance, and contact information for comprehensive insights.",
    join1_corporate_enterprise_title: "Enterprise",
    join1_corporate_enterprise_price: "$199 /month",
    join1_corporate_enterprise_content:
      "Unlock unlimited company profile views with detailed basic, product, finance, and contact information for extensive exploration. Added with a personalized consultation service from industry experts",
    join1_pay: "Pay",
  },
  kr: {
    nav1: "Why Startline",
    nav2: "서비스",
    nav3: "고객지원",
    nav4: "자주하는 질문",
    nav5: "문의하기",
    nav6: "로그인",
    nav7: "구독",
    index_title: "당신의 출발을 Startline과 함께",
    index_slogan: "스타트업과 기업을 위한 혁신의 시작",
    index_context: "저희는 스타트업과 기업 간의 파트너십을 만들어 드립니다",
    join_now: "구독",
    weekly_startline: "이번주 Startline에서..",
    our_product: "기능 소개",
    product_slogan: "Startline에서부터 스타트업과 기업의 미래를 위한 끊임 없는 발전",
    feature_title_1: "맞춤형",
    feature_slogan_1: "고객의 니즈를 파악하는 맞춤형 AI 기반 솔루션",
    feature_content_1: "원하는 것을 알려주시면 저희가 니즈에 맞게 맞춰 드립니다.",
    learn_more_1: "더 보기",
    learn_more_2: "더 보기",
    learn_more_3: "더 보기",
    feature_title_2: "실시간",
    feature_slogan_2: "최신 정보를 제공하는 실시간 데이터 플랫폼",
    feature_content_2: "최신 정보를 제공하기 위해 저희는 최선을 다할것 입니다.",
    feature_title_3: "네트워킹",
    feature_slogan_3: "네트워크를 확장할 수 있는 대화형 소셜 채널",
    feature_content_3: "스타트업이든 기업이든 상관 없습니다! 이 시대의 혁신 기술을 찾기 위해 저희 플랫폼에 가입 하세요",
    simeff: "간편하고 효율적인 플랫폼",
    simeff_title: "5분만에 사용 가능한 당신의 스타트업 데이터 플랫폼",
    simeff_content: "무료 체험",
    simeff_demo: "데모 신청하기",
    partners_clients: "파트너 및 고객",
    whatwedo: "소개",
    whatwedo_slogan: "Startline은 고객들의 고충 해결할 솔루션을 찾아 드립니다",
    whatwedo_content: "많은 플랫폼들은 값비싼 비용만 요구하면서 필요한 정보를 효과적으로 전달 해 주고 있지 않습니다",
    get_started: "시작하기",
    problem_1: "Startline이 발견한 문제점",
    problem_title_1: "많은 플랫폼들이 스타트업과 기업간의 연결고리를 끊어 버리고 있습니다",
    problem_topic_low_outreach: "부족한 접근성",
    problem_content_low_outreach:
      "스타트업은 새로운 제품을 홍보 할 채널을 찾는 데 어려움을 겪으며, 기업은 필요한 혁신 솔루션을 발견하는 데 어려움을 겪고 있습니다",
    problem_topic_data_inaccuracy: "데이터 불일치",
    problem_content_data_inaccuracy:
      "오래되고  검증되지 않은 데이터는 요구 사항을 정확하게 식별하여 관련 솔루션을 찾는데 어려움을 발생 시켜 신뢰할 수 없는 검색 결과를 제공합니다",
    problem_topic_complex_engagement: "어려운 이해관계",
    problem_content_complex_engagement:
      "기업과 스타트업은 종종 서로의 요구사항을 완전히 이해하는데 많은 시간을 소비하게 하여 기술 선별 과정을 복잡하게 만듭니다",
    problem_topic_lack_of_manpower: "인력 부족",
    problem_content_lack_of_manpower: "스타트업과 기업 간의 원활한 소통을 유지하기 위한 충분한 자원과 인력이 부족합니다",
    problem_topic_poor_visualization: "복잡한 데이터 정리",
    problem_content_poor_visualization: "복잡한 데이터 정리와 부족한 사용자 맞춤화로 사용자가 중요 정보를 효율적으로 찾기 어렵습니다",
    lets_fix: "시작하기",
    solution: "Startline 솔류션",
    solution_title: "Startline은 스타트업과 기업들의 위한 소셜미디어입니다",
    solution_startup_slogan: "스타트업",
    solution_startup_content: "여러분의 기술을 제일 필요하는 고객을 찾아 드립니다",
    solution_corporate_slogan: "기업",
    solution_corporate_content: "여러분의 고충을 해결 할 수 있는 기술을 찾아 드립니다",
    try_startline: "바로 시작하기",
    how_it_works: "Startline의 워크플로우",
    how_it_works_slogan_1: "Startline은 여러 데이터를 융합하고 검증하여 최상의 정보를 제공합니다",
    how_it_works_content_1: "맞춤형 데이터 플랫폼으로서 고객이 필요한 정보를 매일 추천 해드립니다",
    how_it_works_option_1: "양과 질 모두 겸비한 플랫폼",
    how_it_works_option_content_1: "다양한 방법으로 제공 될 정보 수집",
    how_it_works_option_2: "회사 정보",
    how_it_works_option_content_2: "수집한 정보를 꼼꼼히 검토해 Startline만의 방식으로 재해석",
    how_it_works_option_3: "고객 맞춤형",
    how_it_works_option_content_3: "사용하면 사용할수록 똑똑해지는 Startline, 고객과 함께 성장하는 데이터 플랫폼",
    how_it_works_slogan_2: "모든 고객을 위해 맞춤형으로 성장하는 인공지능 데이터 플렛폼",
    how_it_works_content_2: "인공지능을 사용해 정확하고 필요한 정보만 제공하여 신속하게 업무를 수행 할 수 있도록 보조합니다",
    how_it_works_1: "Startline의 워크플로우",

    how_it_works_title_integrate_data: "데이터 수집/통합",
    how_it_works_content_integrate_data: "수집한 데이터를 수차례 검토해 효율적인 업무 진행을 도와 드립니다.",
    how_it_works_title_processing_data: "데이터 정리",
    how_it_works_content_processing_data: "수작업을 통해 정리한 데이터를 인공지능을 사용해 한번 더 정리, 검토하여 제공 드립니다.",
    how_it_works_title_creating_insights: "데이터 제공",
    how_it_works_content_creating_insights: "인공지능을 사용해 사용자의 니즈를 파악하고 맞춤형 정보를 제공합니다.",

    how_it_works_title_integrate_data_1: "데이터 수집/통합",
    how_it_works_content_integrate_data_1: "수집한 데이터를 수차례 검토해 효율적인 업무 진행을 도와 드립니다.",
    how_it_works_title_processing_data_1: "데이터 정리",
    how_it_works_content_processing_data_1: "수작업을 통해 정리한 데이터를 인공지능을 사용해 한번 더 정리, 검토하여 제공 드립니다.",
    how_it_works_title_creating_insights_1: "데이터 제공",
    how_it_works_content_creating_insights_1: "인공지능을 사용해 사용자의 니즈를 파악하고 맞춤형 정보를 제공합니다.",

    how_it_works_title_integrate_data_2: "데이터 수집/통합",
    how_it_works_content_integrate_data_2: "수집한 데이터를 수차례 검토해 효율적인 업무 진행을 도와 드립니다.",
    how_it_works_title_processing_data_2: "데이터 정리",
    how_it_works_content_processing_data_2: "수작업을 통해 정리한 데이터를 인공지능을 사용해 한번 더 정리, 검토하여 제공 드립니다.",
    how_it_works_title_creating_insights_2: "데이터 제공",
    how_it_works_content_creating_insights_2: "인공지능을 사용해 사용자의 니즈를 파악하고 맞춤형 정보를 제공합니다.",

    how_it_works_slogan_3: "Startline 솔루션을 사용해 최상의 업무 효율성을 느껴보세요",
    why_startline_title_exceptional_data_quality: "최상의 데이터",
    why_startline_content_exceptional_data_quality: "정보를 검토하고 검증하여 제공하며 목표를 달성할 때까지 동행합니다",
    why_startline_title_indepth_data: "밀도 높은 데이터",
    why_startline_content_indepth_data: "면밀한 검토로 차원이 다른, 심층적인 정보를 제공합니다.",
    why_startline_title_extensive_access: "높은 수준의의 데이터 접근성",
    why_startline_content_extensive_acess: "차원이 다른 데이터를 제공합니다",
    why_startline_title_efficiency: "최상의 효율성",
    why_startline_content_efficiency: "업무 효율을 한단계 올려줄 Startline",
    why_startline_title_complete_solution: "최적의 솔루션",
    why_startline_content_complete_solution: "다량 데이터를 재해석하여 솔루션을 제공합니다",
    why_startline_title_fully_automated: "자동화 솔류션",
    why_startline_content_fully_automated: "새로운 정보를 매일 제공하기 위해 쉬지 않고 있습니다",
    questions: "질문이 있으신가요? 언제든지 연락주세요",
    pricing_1: "요금 소개",
    pricing_slogan: "필요에 맞는 요금제를 선택하세요",
    pricing_free: "무료",
    pricing_free_price: "$0",
    pricing_free_tag: "글로벌 데이터베이스",
    pricing_free_feature_1: "Startline의 AI 기반 매칭 기능 활성화",
    pricing_free_feature_2: "100개의 회사 프로필 검색",
    pricing_free_feature_3: "기본 정보에 대한 엑세스",
    pricing_business: "비지니스",
    pricing_business_price: "월 $49",
    pricing_business_tag_1: "글로벌 데이터베이스",
    pricing_business_tag_2: "데이터 커스터마이징",
    pricing_business_feature_1: "Startline의 AI 기반 매칭 기능 활성화",
    pricing_business_feature_2: "600개의 회사 프로필 검색",
    pricing_business_feature_3: "전담 관리자를 통해 맞춤형 콘텐츠를 받아보세요",
    pricing_business_feature_4: "무료 업그레이드",
    pricing_enterprise: "기업",
    pricing_enterprise_price: "월 $199",
    pricing_enterprise_tag_1: "글로벌 데이터베이스",
    pricing_enterprise_tag_2: "데이터 커스터마이징",
    pricing_enterprise_tag_3: "컨설팅 서비스",
    pricing_enterprise_feature_1: "Startline의 AI 기반 매칭 기능 활성화",
    pricing_enterprise_feature_2: "무제한 회사 프로필 검색",
    pricing_enterprise_feature_3: "전담 관리자를 통해 맞춤형 콘텐츠를 받아보세요",
    pricing_enterprise_feature_4: "전문가로부터 전문 컨설팅 지원 받기",
    pricing_enterprise_feature_5: "무료 업그레이드",
    pricing_enterprise_feature_6: "최대 5명의 팀원과 협업",
    pricing_price_usd: "모든 요금은 USD 입니다",
    questions_slogan: "저희는 여러분을 위해 24시간 대기 하고 있습니다",
    questions_content: "바로 시작하기",
    questions_contact: "문의하기",
    contact: "문의하기",
    contact_question_1: "문의유형",
    contact_question_2: "시장 정보 찾기",
    contact_question_3: "전략적 파트너십 탐색",
    contact_question_4: "추가 서비스 문의",
    contact_question_5: "Startline 고객 평가",
    contact_question_6: "기타",
    price_ready_to_start: "Startline과 함께 할 준비 되셨나요?",
    price_kickstart_innovation: "Startline과 함께 성장하기",
    price_try_startline_now: "바로 시작하기",
    login_startup: "스타트업",
    login_corporate: "기업",
    login_welcome_back: "환영합니다",
    login_startup_slogan: "여러분의 무궁무진한 미래를 위해",
    login_corporate_slogan: "혁신 기술들과 바로 연결하기",
    login_work_email: "회사 이메일",
    login_password: "비밀번호",
    login_remember: "다음에도 사용하기",
    login_forgot_pwd: "비밀번호 찾기",
    login_sign_in: "로그인",
    login_sign_up: "처음이신가요? 회원 가입",
    join_title: "Startline에 환영합니다",
    join_slogan: "저희와 함께 성장해요",
    join_username: "아이디",
    join_input_username: "아이디를 입력해 주십시오.",
    join_pwd: "비밀번호",
    join_name: "성함",
    join_work_email: "회사 이메일",
    join_remember: "다음에도 사용하기",
    join_forgot_pwd: "비밀번호 찾기",
    join_tc_pp_content: "가입함으로써 귀하는 당사의 이용 약관 및 개인정보 수집 및 이용에 동의합니다",
    join_sign_up: "회원 가입",
    join_sign_in: "이미 계정이 있으신가요? 로그인",
    join1_title: "Startline에 환영합니다",
    join1_select: "서비스 선택",
    join1_faq_1: "구독한 서비스를 어떻게 변경하나요?",
    join1_faq_ans_1: "설정 > 구독으로 이동하여  구독 서비스를 변경 할 수 있습니다.",
    join1_faq_2: "추가 문의 사항은 어디로 하면 되나요?",
    join1_faq_ans_2: "자주하는 질문이나 문의하기를 사용해 보세요!",
    join1_startup: "스타트업",
    join1_startup_content: "프로필 페이지를 통해 기업 사용자에게 제품을 무료로 선보입니다!",
    join1_corporate_free_title: "무료",
    join1_corporate_free_price: "$0",
    join1_corporate_free_content: "100개의 회사 프로필을 무료로 검색하세요.",
    join1_corporate_business_title: "비지니스",
    join1_corporate_business_price: "월 $49",
    join1_corporate_business_content: "더 풍족한 데이터로 600개의 회사 프로필을 검색하여 베이직, 제품, 재무 및 연락처를 검색해 보세요!",
    join1_corporate_enterprise_title: "기업",
    join1_corporate_enterprise_price: "월 $199",
    join1_corporate_enterprise_content:
      "무제한 회사 프로필 열람을 가능하게 해 광범위한 탐색을 즐기세요. Startline을 활용하여 업계 전문가와의 맞춤 상담 서비스를 경험해보세요!",
    join1_pay: "결제하기",
  },

  cn: {
    nav1: "为什么选择Startline",
    nav2: "价格",
    nav3: "资源",
    nav4: "支持",
    nav5: "联系",
    nav6: "登录",
    nav7: "加入",
    index_title: "我们是Startline",
    index_slogan: "创新从这里开始，面向初创企业和大型企业。",
    index_context: "我们促进初创企业与大型企业之间的合作伙伴关系。",
    join_now: "立即加入",
    weekly_startline: "本周Startline精选",
    our_product: "我们的产品",
    product_slogan: "Startline为初创企业和大型企业赋能未来",
    feature_title_1: "个性化",
    feature_slogan_1: "根据您的独特需求量身定制的推荐企业",
    feature_content_1: "每个用户需求各异，告诉我们您想要什么，我们为您提供！",
    learn_more_1: "了解更多",
    feature_title_2: "即时洞察",
    feature_slogan_2: "实时数据平台，提供最新信息",
    feature_content_2: "我们的平台全天候运行，望让您随时了解最新动态。",
    learn_more_2: "了解更多",
    feature_title_3: "新连接",
    feature_slogan_3: "一个互动社交平台，扩展您的网络",
    feature_content_3: "无论您是创业者还是企业用户，我们都能满足您的需求。加入我们的生态系统，与引领潮流的公司建立联系！",
    learn_more_3: "了解更多",
    simeff: "简单，高效",
    simeff_title: "您的初创企业数据智能平台 - 5分钟内即可使用",
    simeff_content: "免费使用Startline",
    simeff_demo: "请求免费演示",
    partners_clients: "合作伙伴和客户",
    whatwedo: "我们做什么",
    whatwedo_slogan: "我们看到问题，并希望为您解决它",
    whatwedo_content: "集中化的平台正在破坏初创企业与大型企业之间的桥梁，使获取有价值的信息变得更加困难，阻碍了商业增长，并提高了成本。",
    get_started: "开始使用",
    questions: "有问题？与我们联系",
    questions_slogan: "我们全天候为您提供帮助",
    questions_content: "立即试用Startline",
    questions_contact: "联系我们",
    problem_1: "问题",
    problem_title_1: "集中化的平台破坏了初创企业与大型企业之间的桥梁",
    problem_topic_low_outreach: "低效触达",
    problem_content_low_outreach: "初创企业在寻找有效渠道展示其产品方面面临困难，而大型企业则难以发现满足其业务需求的创新解决方案.",
    problem_topic_data_inaccuracy: "数据不准确",
    problem_content_data_inaccuracy: "过时和未经验证的数据妨碍了用户精准识别企业需求的能力，导致搜索结果不可靠.",
    problem_topic_complex_engagement: "复杂的互动",
    problem_content_complex_engagement: "大型企业和初创企业之间的互动过程往往较长，因为双方都难以完全理解对方的需求和期望.",
    problem_topic_lack_of_manpower: "人力资源不足",
    problem_content_lack_of_manpower: "维持初创企业与大型企业之间强大联系的资源和人力不足.",
    problem_topic_poor_visualization: "可视化效果差",
    problem_content_poor_visualization: "结构不良的界面和缺乏个性化使用户难以高效找到关键信息.",
    lets_fix: "让我们来解决它",
    solution: "我们的解决方案",
    solution_title: "Startline是一个为大型企业和初创企业提供的社交平台",
    solution_startup_slogan: "对于初创企业",
    solution_startup_content: "我们提升您的技术，并为与最需要的企业合作创造机会.",
    solution_corporate_slogan: "对于大型企业",
    solution_corporate_content: "我们为你链接完美解决方案，以应对你的挑战.",
    try_startline: "试用Startline",
    how_it_works: "如何运作",
    how_it_works_slogan_1: "Startline融合和验证多个数据源，以提供最佳信息",
    how_it_works_content_1: "我们从自己准确且最新的数据库中筛选出你所需的信息.",
    how_it_works_option_1: "多个数据源",
    how_it_works_option_content_1: "我们从各种来源收集信息.",
    how_it_works_option_2: "公司资料",
    how_it_works_option_content_2: "我们精心整理的数据库概述了每家公司的信息.",
    how_it_works_option_3: "用户反馈",
    how_it_works_option_content_3: "我们的匹配算法会随着反馈不断改进.",
    how_it_works_slogan_2: "我们的数据驱动技术为你提供定制化人工智能模型.",
    how_it_works_content_2: "我们利用人工智能提供清晰、相关和及时的洞察，帮助企业和初创公司相互链接.",
    how_it_works_1: "如何运作",

    how_it_works_title_integrate_data: "整合数据",
    how_it_works_content_integrate_data: "我们将积累的数据转化为结构化数据集.",
    how_it_works_title_processing_data: "处理数据",
    how_it_works_content_processing_data: "我们利用机器学习对公司进行分类、标记和评估.",
    how_it_works_title_creating_insights: "创建洞察",
    how_it_works_content_creating_insights: "通过人工智能，我们确定最重要的信息，并将您与满足您需求的公司匹配.",

    how_it_works_title_integrate_data_1: "整合数据",
    how_it_works_content_integrate_data_1: "我们将积累的数据转化为结构化数据集.",
    how_it_works_title_processing_data_1: "处理数据",
    how_it_works_content_processing_data_1: "我们利用机器学习对公司进行分类、标记和评估.",
    how_it_works_title_creating_insights_1: "创建洞察",
    how_it_works_content_creating_insights_1: "通过人工智能，我们确定最重要的信息，并将您与满足您需求的公司匹配.",

    how_it_works_title_integrate_data_2: "整合数据",
    how_it_works_content_integrate_data_2: "我们将积累的数据转化为结构化数据集.",
    how_it_works_title_processing_data_2: "处理数据",
    how_it_works_content_processing_data_2: "我们利用机器学习对公司进行分类、标记和评估.",
    how_it_works_title_creating_insights_2: "创建洞察",
    how_it_works_content_creating_insights_2: "通过人工智能，我们确定最重要的信息，并将您与满足您需求的公司匹配.",

    how_it_works_slogan_3: "我们的匹配过程确保每个请求都有相应的解决方案.",
    why_startline_title_exceptional_data_quality: "高质量数据",
    why_startline_content_exceptional_data_quality: "我们的人工智能模型会抓取和清理数据，直到达到你的需求.",
    why_startline_title_indepth_data: "深入的数据",
    why_startline_content_indepth_data: "我们提供公司真实背景信息。这些信息将协助你验证真实需求.",
    why_startline_title_extensive_access: "广泛的访问权限",
    why_startline_content_extensive_acess: "访问其他人无法进入的科技市场.",
    why_startline_title_efficiency: "最高效的方式",
    why_startline_content_efficiency: "寻找您所需内容的最简单、最高效的方法.",
    why_startline_title_complete_solution: "完整的解决方案",
    why_startline_content_complete_solution: "我们提供的是解决方案，而不是一堆无序数据.",
    why_startline_title_fully_automated: "完全自动化",
    why_startline_content_fully_automated: "我们的人工智能模型允许平台全天候工作地满足你的业务需求，并每天提供即时信息.",
    questions_price: "所有价格均以美元计。",
    pricing_1: "价格",
    pricing_slogan: "选择符合您需求的计划.",
    pricing_free: "永久免费",
    pricing_free_price: "$0",
    pricing_free_tag: "全球数据库",
    pricing_free_feature_1: "解锁Startline的人工智能匹配功能",
    pricing_free_feature_2: "每月搜索100个公司资料，包含基本内容",
    pricing_free_feature_3: "访问基本信息",
    pricing_business: "商务版",
    pricing_business_price: "每月 $49美金",
    pricing_business_tag_1: "全球数据库",
    pricing_business_tag_2: "数据定制",
    pricing_business_feature_1: "解锁Startline的人工智能匹配功能",
    pricing_business_feature_2: "每月搜索600个公司完整信息",
    pricing_business_feature_3: "从我们的专属客户经理那里获得定制内容",
    pricing_business_feature_4: "免费升级到未来平台新功能",
    pricing_enterprise: "企业版",
    pricing_enterprise_price: "每月 $199美金",
    pricing_enterprise_tag_1: "全球数据库",
    pricing_enterprise_tag_2: "数据定制",
    pricing_enterprise_tag_3: "专业咨询服务支持",
    pricing_enterprise_feature_1: "解锁Startline的人工智能匹配功能",
    pricing_enterprise_feature_2: "无限制访问公司完整信息",
    pricing_enterprise_feature_3: "从我们专属客户经理那里获得定制内容",
    pricing_enterprise_feature_4: "获得来自行业知名专家的专业咨询支持",
    pricing_enterprise_feature_5: "免费升级到未来平台功能",
    pricing_enterprise_feature_6: "与最多5名团队成员协作",
    pricing_price_usd: "所有价格均以美元计。",
    contact: "联系",
    contact_question_1: "请您选择联系的原因：",
    contact_question_2: "寻求详细的市场信息",
    contact_question_3: "探索潜在的战略合作机会",
    contact_question_4: "有兴趣了解其他服务",
    contact_question_5: "对平台/服务提供反馈",
    contact_question_6: "其他咨询（请具体说明）",
    price_ready_to_start: "准备开始了吗？",
    price_kickstart_innovation: "与我们一起启动创新",
    price_try_startline_now: "立即试用Startline",
    login_startup: "初创企业",
    login_corporate: "企业用户",
    login_welcome_back: "欢迎回来",
    login_startup_slogan: "为您的解决方案而奋斗",
    login_corporate_slogan: "为您与解决方案建立联系",
    login_work_email: "工作邮箱",
    login_password: "密码",
    login_remember: "记住我",
    login_forgot_pwd: "忘记密码？",
    login_sign_in: "登录",
    login_sign_up: "没有账号？注册",
    join: "加入",
    join_title: "欢迎来到Startline",
    join_slogan: "与我们一起启动创新",
    join_username: "用户名",
    join_pwd: "密码",
    join_name: "姓名",
    join_work_email: "工作邮箱",
    join_remember: "记住我",
    join_forgot_pwd: "忘记密码？",
    join_tc_pp_content: "注册即表示您同意我们的条款和条件以及隐私政策。",
    join_sign_up: "注册",
    join_sign_in: "已经有账号？登录",
    join1_title: "欢迎来到Startline",
    join1_select: "请选择您的计划",
    join1_faq_1: "我可以稍后更改我的计划吗？",
    join1_faq_ans_1: "当然可以！您可以通过进入设置 > 计划设置来更改您的计划。",
    join1_faq_2: "我的问题并没有全部得到解答，我该联系谁？",
    join1_faq_ans_2: "请查看我们的支持页面或联系我们！",
    join1_startup: "我是初创企业",
    join1_startup_content: "通过个性化的个人主页向企业用户展示您的产品，完全免费！",
    join1_corporate_free_title: "免费",
    join1_corporate_free_price: "$0",
    join1_corporate_free_content: "免费访问100家公司资料，包含公司网站链接和员工人数等基本信息。",
    join1_corporate_business_title: "商务版",
    join1_corporate_business_price: "每月 $49美金",
    join1_corporate_business_content: "深度访问600家公司详细资料，包含基本信息、产品信息、财务信息和联系方式，以获取全面的洞察。",
    join1_corporate_enterprise_title: "企业版",
    join1_corporate_enterprise_price: "每月 $199美金",
    join1_corporate_enterprise_content:
      "解锁全部公司信息，包含详细的基本信息、产品信息、财务信息和联系信息，助力深度调研。同时还提供行业专家的定制化咨询服务。",
    join1_pay: "付款",
  },

  jp: {
    nav1: "なぜStartlineなのか",
    nav2: "価格",
    nav3: "リソース",
    nav4: "サポート ",
    nav5: "連絡",
    nav6: "ログイン",
    nav7: "参加する",
    index_title: "私たちはStartlineです",
    index_slogan: "スタートアップと企業のための革新が始まる場所。",
    index_context: "私たちはスタートアップと企業の協力的なパートナーシップを強化します.",
    join_now: "今すぐ参加",
    weekly_startline: "今週のStartline",
    our_product: "私たちの製品",
    product_slogan: "スタートアップと企業の未来をStartlineで実現する",
    feature_title_1: "パーソナライズ",
    feature_slogan_1: "あなたの独自のニーズに合ったカスタマイズされた提案",
    feature_content_1: "誰もが異なるニーズを持っています。あなたが望むことを教えてください。私たちはそれを提供します！",
    learn_more_1: "詳しく見る",
    feature_title_2: "タイムリーなインサイト",
    feature_slogan_2: "最新情報を提供するリアルタイムデータプラットフォーム",
    feature_content_2: "あなたに最新情報をお届けしたい。私たちのプラットフォームは24時間365日稼働しており、最新の情報を見つけます.",
    learn_more_2: "詳しく見る",
    feature_title_3: "新しいつながり",
    feature_slogan_3: "ネットワークを拡大するためのインタラクティブなソーシャルチャンネル",
    feature_content_3:
      "あなたがスタートアップであれ、企業であれ、私たちがサポートします。トレンドをリードする企業とつながるために、私たちのエコシステムに参加してください！",
    learn_more_3: "詳しく見る",
    simeff: "シンプルで効率的",
    simeff_title: "あなたのスタートアップデータインテリジェンスプラットフォーム - 5分で使用可能",
    simeff_content: "Startlineを無料で使用",
    simeff_demo: "無料デモをリクエスト",

    partners_clients: "パートナーとクライアント",
    whatwedo: "私たちの業務",
    whatwedo_slogan: "私たちは問題を見つけ、それを解決したいと思っています",
    whatwedo_content:
      "中央集権的なプラットフォームは、スタートアップと企業の間の橋を焼き、貴重な情報へのアクセスを難しくし、ビジネスの成長を妨げ、コストを押し上げています.",
    get_started: "始める",
    questions: "質問がありますか？私たちに話してください",
    questions_slogan: "私たちは24時間体制であなたをサポートします",
    questions_content: "今すぐStartlineを試す",
    questions_contact: "お問い合わせ",
    problem_1: "問題",
    problem_title_1: "中央集権的なプラットフォームは、スタートアップと企業の間の橋を焼いています。",
    problem_topic_low_outreach: "低い接触率",
    problem_content_low_outreach:
      "スタートアップは製品を展示するための効果的なチャネルを見つけるのに苦労し、企業はビジネスニーズに合った革新的なソリューションを見つけるのが難しいです。",
    problem_topic_data_inaccuracy: "データの不正確さ",
    problem_content_data_inaccuracy:
      "古くて未確認のデータは、関連するソリューションを見つけたり、企業のニーズを正確に特定したりする能力を妨げ、信頼できない検索結果をもたらします。",
    problem_topic_complex_engagement: "複雑なエンゲージメント",
    problem_content_complex_engagement:
      "大企業とスタートアップの間では、相手のニーズや期待を完全に理解するのに苦労するため、エンゲージメントプロセスが長引くことがあります。",
    problem_topic_lack_of_manpower: "人手不足",
    problem_content_lack_of_manpower: "スタートアップと企業の間で強固な関係を維持するためのリソースと人手が不足しています。",
    problem_topic_poor_visualization: "視覚化が不十分",
    problem_content_poor_visualization:
      "構造が不十分なインターフェースとパーソナライズの欠如により、ユーザーが重要な情報を効率的に見つけることが難しくなっています。",
    lets_fix: "解決しましょう",
    solution: "私たちのソリューション",
    solution_title: "Startlineは企業とスタートアップのためのソーシャルプラットフォームです。",
    solution_startup_slogan: "スタートアップ向け",
    solution_startup_content: "私たちはあなたの技術を強化し、最も必要としている人々とのコラボレーションの道を作ります。",
    solution_corporate_slogan: "企業向け",
    solution_corporate_content: "私たちはあなたを、あなたの課題に対する完璧なソリューションを持つ新興イノベーターとつなげます。",
    try_startline: "今すぐStartlineを試す",
    how_it_works: "仕組み",
    how_it_works_slogan_1: "Startlineは複数のデータソースを統合し、検証して最適な情報を提供します。",
    how_it_works_content_1: "私たちは、自社の正確で最新のデータベースから必要な情報を選び出します。",
    how_it_works_option_1: "複数のデータソース",
    how_it_works_option_content_1: "私たちはさまざまなソースから情報を収集します.",
    how_it_works_option_2: "会社プロフィール",
    how_it_works_option_content_2: "私たちのキュレーションされたデータベースは、各会社の情報を概説しています.",
    how_it_works_option_3: "ユーザーフィードバック",
    how_it_works_option_content_3: "私たちのマッチングアルゴリズムは、フィードバックによって常に改善されます.",
    how_it_works_slogan_2: "私たちのデータ駆動型技術には、あなたのために最適化されたAIモデルがあります。",
    how_it_works_content_2:
      "私たちはAIを活用して、企業とスタートアップが互いに見つけ合うための明確で関連性のあるタイムリーなインサイトを提供します.",
    how_it_works_1: "仕組み",

    how_it_works_title_integrate_data: "データの統合",
    how_it_works_content_integrate_data: "私たちは蓄積されたデータを構造化されたデータセットに変換します.",
    how_it_works_title_processing_data: "データの処理",
    how_it_works_content_processing_data: "私たちは機械学習を活用して、企業を分類、タグ付け、評価します.",
    how_it_works_title_creating_insights: "インサイトの作成",
    how_it_works_content_creating_insights: "AIを通じて、最も重要な情報を特定し、あなたのニーズに合った企業とマッチングします.",

    how_it_works_title_integrate_data_1: "データの統合",
    how_it_works_content_integrate_data_1: "私たちは蓄積されたデータを構造化されたデータセットに変換します.",
    how_it_works_title_processing_data_1: "データの処理",
    how_it_works_content_processing_data_1: "私たちは機械学習を活用して、企業を分類、タグ付け、評価します.",
    how_it_works_title_creating_insights_1: "インサイトの作成",
    how_it_works_content_creating_insights_1: "AIを通じて、最も重要な情報を特定し、あなたのニーズに合った企業とマッチングします.",

    how_it_works_title_integrate_data_2: "データの統合",
    how_it_works_content_integrate_data_2: "私たちは蓄積されたデータを構造化されたデータセットに変換します.",
    how_it_works_title_processing_data_2: "データの処理",
    how_it_works_content_processing_data_2: "私たちは機械学習を活用して、企業を分類、タグ付け、評価します.",
    how_it_works_title_creating_insights_2: "インサイトの作成",
    how_it_works_content_creating_insights_2: "AIを通じて、最も重要な情報を特定し、あなたのニーズに合った企業とマッチングします.",

    how_it_works_slogan_3: "私たちのマッチングプロセスは、各リクエストが解決策に合致することを保証します.",
    why_startline_title_exceptional_data_quality: "卓越したデータ品質",
    why_startline_content_exceptional_data_quality:
      "私たちのAIモデルは、あなたが満足するまでデータをスクレイピングし、クリーンアップします.",
    why_startline_title_indepth_data: "深いデータ",
    why_startline_content_indepth_data:
      "私たちは企業の背後にある本当のストーリーを提供します。これらのストーリーは、あなたが本当に必要なものを検証するのに役立ちます.",
    why_startline_title_extensive_access: "広範なアクセス",
    why_startline_content_extensive_acess: "他の誰も持っていないテクノロジー市場へのアクセス.",
    why_startline_title_efficiency: "最高の効率",
    why_startline_content_efficiency: "必要なものを探すための最もシンプルで効率的な方法.",
    why_startline_title_complete_solution: "完全なソリューション",
    why_startline_content_complete_solution: "私たちはデータベースの山ではなく、ソリューションを提供します.",
    why_startline_title_fully_automated: "完全自動化",
    why_startline_content_fully_automated:
      "私たちのAIモデルは、あなたのニーズを満たし、毎日新しい情報を提供するために、24時間365日稼働します.",
    questions_price: "すべての価格はUSD（米ドル）です。",
    pricing_1: "価格 ",
    pricing_slogan: "あなたのニーズに合ったプランを選んでください。",
    pricing_free: "永遠に無料",
    pricing_free_price: "$0",
    pricing_free_tag: "グローバルデータベース",
    pricing_free_feature_1: "StartlineのAI駆動のマッチング機能をアンロック",
    pricing_free_feature_2: "毎月100社のプロフィールを基本コンテンツで検索",
    pricing_free_feature_3: "基本情報にアクセス",
    pricing_business: "ビジネスプラン",
    pricing_business_price: "月額 $49",
    pricing_business_tag_1: "グローバルデータベース",
    pricing_business_tag_2: "データカスタマイズ",
    pricing_business_feature_1: "StartlineのAI駆動のマッチング機能をアンロック",
    pricing_business_feature_2: "毎月600社のプロフィールをフルコンテンツで検索",
    pricing_business_feature_3: "専任のサクセスマネージャーからカスタマイズされたコンテンツを受け取る",
    pricing_business_feature_4: "将来のプラットフォーム機能への無料アップグレード",
    pricing_enterprise: "法人プラン",
    pricing_enterprise_price: "月額 $199",
    pricing_enterprise_tag_1: "グローバルデータベース",
    pricing_enterprise_tag_2: "データカスタマイズ",
    pricing_enterprise_tag_3: "プロフェッショナルコンサルティングサポート",
    pricing_enterprise_feature_1: "StartlineのAI駆動のマッチング機能をアンロック",
    pricing_enterprise_feature_2: "無制限の会社プロフィールにアクセスし、完全な結果を取得",
    pricing_enterprise_feature_3: "指定されたサクセスマネージャーからカスタマイズされたコンテンツを受け取る",
    pricing_enterprise_feature_4: "業界の著名な専門家からプロフェッショナルなコンサルティングサポートを受ける",
    pricing_enterprise_feature_5: "将来のプラットフォーム機能への無料アップグレード",
    pricing_enterprise_feature_6: "最大5名のチームメンバーと協力",
    pricing_price_usd: "すべての価格はUSD（米ドル）です。",
    contact: "連絡",
    contact_question_1: "お問い合わせの理由を選択してください：",
    contact_question_2: "詳細な市場情報を求めている",
    contact_question_3: "潜在的な戦略的パートナーシップの機会を探っている",
    contact_question_4: "追加サービスのレビューに興味がある",
    contact_question_5: "プラットフォーム/サービスに関するフィードバックを提供する",
    contact_question_6: "その他のお問い合わせ（具体的にご記入ください）",

    price_ready_to_start: "始める準備はできましたか？",
    price_kickstart_innovation: "私たちと一緒にイノベーションをスタートさせましょう",
    price_try_startline_now: "今すぐStartlineを試す",
    login_startup: "スタートアップ",
    login_corporate: "企業の",
    login_welcome_back: "お帰りなさい",
    login_startup_slogan: "あなたのソリューションを支援するために",
    login_corporate_slogan: "ソリューションとつながるために",
    login_work_email: "仕事用メール",
    login_password: "パスワード",
    login_remember: "私を覚えておく",
    login_forgot_pwd: "パスワードを忘れましたか？",
    login_sign_in: "サインイン",
    login_sign_up: "アカウントをお持ちでないですか？ サインアップ",
    join_title: "Startlineへようこそ",
    join_slogan: "私たちと一緒にイノベーションをスタートさせましょう",
    join_username: "ユーザー名",
    join_input_username: "ユーザー名を入力してください",
    join_pwd: "パスワード",
    join_name: "名前",

    join_work_email: "仕事用メール",
    join_remember: "私を覚えておく",
    join_forgot_pwd: "パスワードを忘れましたか？",
    join_tc_pp_content: "登録することで、私たちの利用規約とプライバシーポリシーに同意したことになります。",
    join_sign_up: "サインアップ",
    join_sign_in: "既にアカウントをお持ちですか？ サインイン",
    join1_title: "Startlineへようこそ",
    join1_select: "プランを選択してください",
    join1_faq_1: "後でプランを変更できますか？",
    join1_faq_ans_1: "もちろんです！設定 > プラン設定に進むことでプランを変更できます。",
    join1_faq_2: "私の質問はすべて答えられていません。誰に連絡すればいいですか？",
    join1_faq_ans_2: "サポートページをご覧いただくか、お問い合わせください！",
    join1_startup: "私はスタートアップです",
    join1_startup_content: "個別のプロフィールページを通じて、企業ユーザーに製品を無料で紹介しましょう！",
    join1_corporate_free_title: "無料",
    join1_corporate_free_price: "$0",
    join1_corporate_free_content: "ウェブサイトリンクや従業員数などの基本情報を含む100社のプロフィールに無料でアクセスできます。",
    join1_corporate_business_title: "ビジネスプラン",
    join1_corporate_business_price: "月額 $49",
    join1_corporate_business_content:
      "600社のプロフィールを深く掘り下げ、基本情報、製品情報、財務情報、連絡先情報を含む包括的なインサイトを得ることができます。",
    join1_corporate_enterprise_title: "法人プラン",
    join1_corporate_enterprise_price: "月額 $199",
    join1_corporate_enterprise_content:
      "詳細な基本情報、製品情報、財務情報、および連絡先情報を含む無制限の会社プロフィールビューを解放し、広範な探索が可能になります。さらに、業界の専門家による個別相談サービスも追加されます。",
    join1_pay: "支払い",
  },
};

export default LANGUAGE;
