const LANGUAGE = {
  en: {
    nav1: "Why Startline",
    nav2: "Price",
    nav3: "Resources",
    nav4: "Support",
    nav5: "Contact",
    nav6: "Login",
    nav7: "Join",
    index_title: "We are the Startline",
    index_slogan: "Where innovation for startups and corporates begins.",
    index_context: "We empower the collaborative partnership between startups and corporates",
    join_now: "Join Now",
    weekly_startline: "This week on Startline",
    our_product: "Our Product",
    product_slogan: "Empowering futures at the Startline for startups and corporates",
    feature_title_1: "PERSONALIZED",
    feature_slogan_1: "Tailored recommendations that fit your unique needs",
    feature_content_1: "Everyone has different needs. Tell us what you want and we will provide it to you!",
    learn_more: "Learn More",
    // Add the rest of the data here
  },
  kr: {
    nav1: "Why Startline",
    nav2: "요금 소개",
    nav3: "고객지원",
    nav4: "자주하는 질문",
    nav5: "문의하기",
    nav6: "로그인",
    nav7: "구독",
    index_title: "당신의 출발을 Startline과 함께",
    index_slogan: "스타트업과 기업을 위한 혁신의 시작",
    index_context: "저희는 스타트업과 기업 간의 파트너십을 만들어 드립니다",
    join_now: "구독",
    weekly_startline: "이번주 Startline에서..",
    our_product: "기능 소개",
    product_slogan: "Startline에서부터 스타트업과 기업의 미래를 위한 끊임 없는 발전",
    feature_title_1: "맞춤형",
    feature_slogan_1: "고객의 니즈를 파악하고 필요에 맞는 맞춤형 추천 알고리즘",
    feature_content_1: "여러 니즈를 위해 저희가 맞춰 드립니다. 원하는 것을 알려주시면 제공해드립니다.",
    learn_more: "더 보기",
    // Add the rest of the data here
  },
};

export default LANGUAGE;
